version: 0.1.{build}

skip_tags: true # avoid deploy to GitHub loop 

# enable patching of dot net core/standard *.csproj files with APPVEYOR version
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

image: Visual Studio 2019

configuration:
- Release

before_build:
- nuget restore -Verbosity quiet

build:
  publish_nuget: true             # package projects with .nuspec files and push to artifacts
  publish_nuget_symbols: false     # generate and publish NuGet symbol packages
  include_nuget_references: false  # add -IncludeReferencedProjects option while packaging NuGet artifacts
  verbosity: minimal              # MSBuild verbosity level

artifacts:
- path: Installer\bin\$(configuration)\net5.0
  name: Installer
  type: zip

deploy:
# GitHub release
- provider: GitHub
  release: $(appveyor_build_version)
  description: 'Release auto generated by AppVeyor'
  auth_token:
    secure: fGVm8Adn/cp+0vP/TKHUVPiJiE4I5ZcBP5WD1GTvIagnWtZuZL7OdYVdPJxri006
  artifact: Installer
  draft: false
  prerelease: false
# nuget.org
- provider: NuGet
  api_key:
    secure: ywrBoIc1n2YEkhbPI3UCwYMQPT8hpxzMIDoHZvDOCZaa4I4uzhXp2LlTDUMruOwP
  skip_symbols: false
  artifact: /.*\.nupkg/