version: 0.1.{build}

skip_tags: true # avoid deploy to GitHub loop 

# enable patching of dot net core/standard *.csproj files with APPVEYOR version
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

image: Visual Studio 2022

configuration:
- Release

before_build:
- nuget restore -Verbosity quiet

build:
  publish_nuget: true             # package projects with .nuspec files and push to artifacts
  publish_nuget_symbols: false     # generate and publish NuGet symbol packages
  include_nuget_references: false  # add -IncludeReferencedProjects option while packaging NuGet artifacts
  verbosity: minimal              # MSBuild verbosity level

artifacts:
- path: Installer\bin\$(configuration)
  name: Installer
  type: zip

deploy:
# GitHub release
- provider: GitHub
  release: $(appveyor_build_version)
  description: 'Release auto generated by AppVeyor'
  auth_token:
    secure: wd4sav5la53QA4mjCgbAQAOoP7aHJgfEfT+ARpjQJ1OxRE6H5fqrIuGQB+Cc/cSm
  artifact: Installer
  draft: false
  prerelease: false
# nuget.org
- provider: NuGet
  api_key:
    secure: /JMjDDHiwiAK5ZV7h+CYszyB/FnZ9P7oPUjSWQML1Z1TuO4ZPB0BGcvF6UfCwIRQ
  skip_symbols: false
  artifact: /.*\.nupkg/